version: '3'
services:
  front:
      tty: true
      container_name: front
      build:
        context: .dockerfiles
        dockerfile: DockerfileFrontend
      ports:
        - 8080:5173
      volumes:
        - ./front:/app
      #command: 'npm run dev'
      depends_on:
        - back
  back:
      tty: true
      container_name: back
      build:
        context: .dockerfiles
        dockerfile: DockerfileBackend
      ports:
        - 8888:8888
      volumes:
        - ./back:/app
      # command: 'composer startup'
      restart: always
      networks:
        - pokedex
networks:
  pokedex:
    driver: bridge